// lib/vector.js
// Vector search using embeddings generated by the MV3 offscreen document.
//
// The actual multilingual-E5 model runs inside offscreen/offscreen.js.
// This file only requests embeddings and performs cosine similarity.

let offscreenReady = false;

/**
 * Create the offscreen document if it does not already exist.
 */
async function ensureOffscreenDocument() {
  if (offscreenReady) return;

  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
    documentUrls: [chrome.runtime.getURL("offscreen/offscreen.html")],
  });

  if (existingContexts.length === 0) {
    await chrome.offscreen.createDocument({
      url: "offscreen/offscreen.html",
      reasons: ["WORKERS"],
      justification: "Run local multilingual E5 embeddings without blocking the service worker.",
    });
  }

  offscreenReady = true;
}

/**
 * Ask the offscreen document to generate a local E5 embedding.
 *
 * @param {string} text
 * @param {"passage"|"query"} type
 * @returns {Promise<number[]>}
 */
export async function embed(text, type = "passage") {
  if (typeof text !== "string" || text.trim().length === 0) {
    throw new Error("Embedding input must be a non-empty string.");
  }

  await ensureOffscreenDocument();

  const response = await chrome.runtime.sendMessage({
    target: "offscreen-embedder",
    action: "EMBED",
    text,
    isQuery: type === "query",
  });

  if (!response?.success) {
    throw new Error(
      response?.error || "Local embedding generation failed."
    );
  }

  if (!Array.isArray(response.embedding)) {
    throw new Error("Invalid embedding returned by offscreen runtime.");
  }

  if (response.embedding.length !== 384) {
    throw new Error(
      `Unexpected embedding dimension: ${response.embedding.length}. Expected 384.`
    );
  }

  return response.embedding;
}

/**
 * Cosine similarity.
 *
 * E5 embeddings are L2-normalized, so dot product is equivalent
 * to cosine similarity.
 */
export function cosineSimilarity(a, b) {
  let dot = 0;

  const length = Math.min(a.length, b.length);

  for (let i = 0; i < length; i++) {
    dot += a[i] * b[i];
  }

  return dot;
}

/**
 * Semantic vector search.
 */
export async function vectorSearch(items, query, k = 10) {
  const queryVec = await embed(query, "query");

  const scores = items
    .filter((item) => item.embedding)
    .map((item) => ({
      id: item.id,
      score: cosineSimilarity(queryVec, item.embedding),
    }));

  return scores
    .sort((a, b) => b.score - a.score)
    .slice(0, k);
}